### ISSUE TITLE
Published QGIS Projects cannot be removed from filesystem

### ISSUE THREAD

**Issue by hdus** [qwc-services/qwc-services-core#5]
A published QGIS Project is stored in `volumes/qgs-resources`. The published does not have the premissions to remove the QGIS Project.

**Comment by manisandro** [comment]
You can now override the UID/GID which runs the qwc services, and set it to the same UID/GID which owns the folders on the host system. See https://github.com/qwc-services/qwc-docker/blob/master/doc/UpgradeNotes.md#upgrading-to-qwc-service-images-v20220126
