### ISSUE TITLE
app_nocache Cache-Control

### ISSUE THREAD

**Issue by TNick** [qwc-services/qwc-services-core#9]
In [app.py](https://github.com/qwc-services/qwc-services-core/blob/7a641fd74d37ce3ce6f8f426c161dd41b413c903/qwc_services_core/app.py#L12) `Cache-Control` is added twice.

```python
r.headers["Cache-Control"] = "no-cache, no-store, must-revalidate"
r.headers["Pragma"] = "no-cache"
r.headers["Expires"] = "0"
r.headers["Cache-Control"] = "public, max-age=0"
```

Not sure which one should be kept in place but this looks like a bug. Maybe [this SO question can shed some light](https://stackoverflow.com/questions/1046966/whats-the-difference-between-cache-control-max-age-0-and-no-cache).

Edit: see test [here](https://github.com/AdvaitaTopCad/qwc-services-core/blob/d80664b657cfbdcb506073b4c2fdc5ec90de6931/qwc_services_core/app_test.py#L28)

**Comment by manisandro** [comment]
Thanks, fixed in 6332f4b668dfc3df5404bb3331077742db3627ac
